version: '3.3'
services:
  jenkins:
    build: .
    user: root
    networks:
      - ci_net
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
  
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    networks:
      - ci_net
    ports:
      - 8888:8081
      - 8889:8082
    volumes:
      - artifactory:/var/opt/jfrog/artifactory
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  jenkins:
  artifactory:

networks:
  ci_net: